require("Biostrings")
require("minqa")
source("em.R")
fdata <- read.table(file="55580488")
fdata <- cbind(fdata, fdata[,1])
fdata <- fdata[, 4:8]
fdata <- t(fdata)
tdata <- read.table(file="46593709")
tdata <- cbind(tdata, tdata[,1])
tdata <- tdata[, 4:8]
tdata <- t(tdata)
if(!exists("ploidy")) ploidy<-"diploid"; cat("##Ploidy:",ploidy,"\n")
if(!exists("dels")) dels<-0.05; cat("##Maximum deletion proportion among considered alleles:",dels,"\n")
if(!exists("bq")) bq<-17; cat("##Minimum base quality for allele to be considered:",bq,"\n")
if(!exists("mq")) mq<-20; cat("##Minimum mapping quality for allele to be considered:",mq,"\n")
if(!exists("ref_ratio")) ref_ratio<-0.9; cat("##Prefiltering reference ratio:",ref_ratio,"\n")
if(!exists("maxcov")) maxcov<-255; cat("##Maximum number of alleles to analyze at each site:",maxcov,"\n")
if(!exists("maxitr")) maxitr<-10000; cat("##Maximum number of EM algorithm iterations of the GeMS multiEM() function:",maxitr,"\n")
if(!exists("paravcf")) paravcf<-NA; cat("##Cores used to parallelize vcf creation:",paravcf,"\n")
if(!exists("cores")) cores<-1; cat("##Cores used:",cores,"\n")
if(!exists("fdrthres")) fdrthres<-0.1; cat("##FDR threshold, if in use:",fdrthres,"\n")
if(!exists("twostepphi")) twostepphi<-0.01; cat("##Two-Step GeMS threshold, if in use:",twostepphi,"\n")
if(!exists("opttol")) opttol<-.Machine$double.eps^0.175; cat("##R's optimize tol parameter:",opttol,"\n")
print("CALLED")
multiEM("A", tdata, c(1),1)
print("UNCALL")
multiEM("C", fdata, c(1),1)
